"""
Django settings for tracetype project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os # Added for os.path.join if needed, though Path is good.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'YOUR_DJANGO_SECRET_KEY_HERE_PLEASE_REPLACE_ME_OR_LOAD_FROM_ENV' # Keep your original secret key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS: Important for when DEBUG = False, but good to set for development too.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# --- Custom Project Specific Settings ---
# Fernet Encryption Key for keylogger
# SECURITY WARNING: For production, load this from an environment variable or a secure file.
# DO NOT COMMIT THIS TO A PUBLIC REPOSITORY IF IT'S YOUR REAL PRODUCTION KEY.
FERNET_KEY = b'YOUR_FERNET_KEY_HERE_PLEASE_REPLACE_ME'
# --- End Custom Project Specific Settings ---


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard.apps.DashboardConfig',  # Your app
    # 'rest_framework', # Uncomment if/when you decide to use Django REST Framework
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # Correct order
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tracetype.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # This line assumes your 'templates' folder is at the project root (same level as manage.py)
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True, # Allows Django to find templates within app directories too (e.g., dashboard/templates/)
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tracetype.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3', # Creates db.sqlite3 in your project root
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC' # Default
TIME_ZONE = 'Asia/Kolkata'  # Your setting

USE_I18N = True

USE_TZ = True # Important for handling datetimes correctly, especially with auto_now/auto_now_add


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'

# This line assumes your 'static' folder for project-wide static files
# is at the project root (same level as manage.py)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Optional: Login/Logout Redirects ---
# These are useful if you implement a custom login for your dashboard,
# or want to control where users go after admin login/logout.
# LOGIN_URL = '/admin/login/' # Or your custom login page for the dashboard
# LOGIN_REDIRECT_URL = '/dashboard/'  # Redirect after successful login to the dashboard home
# LOGOUT_REDIRECT_URL = '/' # Or '/admin/login/' or any other page
# --- End Optional Redirects ---